# Generated by Django 5.0.3 on 2024-03-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('price', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('modelYear', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('codeFipe', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('vehicleType', models.CharField(max_length=50)),
                ('fuelType', models.CharField(max_length=50)),
            ],
        ),
    ]
